### ISSUE TITLE
Geohashing Bot seems to be napping on the job

### ISSUE THREAD

**Issue by bflo-geohasher** [relet/pygeohashing#9]
Looks like the bot that auto-populates the Current events/Main page isn't functioning at the moment as the last day on the Current Events page is Dec 7th. 

~ Pedalpusher

**Comment by aperfectring** [comment]
Yup, the computer which runs it is having issues right now.  I hope to have it temporarily resolved in a day or two.

**Comment by bflo-geohasher** [comment]
Ok, thanks. I don't often go on the IRC channel and I didn't see anything here. Wanted to make sure someone was aware of the issue since it's been a while.

**Comment by aperfectring** [comment]
It's appreciated, because often there's a good chance I haven't noticed.

**Comment by bflo-geohasher** [comment]
Hey aperfectring, any update on this? I saw someone else mentioning an issue on NWoodruff's page that's probably related to this. The Most Active Graticule page he operates is hiccuping since his script can't hit the archive pages.

**Comment by aperfectring** [comment]
I was able to get something up and going last night.  The computer which runs it has now basically died, so I put it onto another computer temporarily until I can replace the one that died.
